services:
  server:
    build: ./server
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development

  client:
    build: ./client
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server