services:

  server:
    build: ./server
    container_name: flask-backend
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      db:
        condition: service_healthy
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
      - NET_ADMIN
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    platform: "linux/amd64"

  client:
    build: ./client
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    depends_on:
      - server

  db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5